version: '3.9'

services:
  postgres:
    image: postgres
    container_name: postgres-docker
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: ndormoy@student.42.fr
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - "80:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always

volumes:
  postgres-data:
  pgadmin-data:
